apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregatorservice-development
  labels:
    app: aggregatorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregatorservice
  template:
    metadata: 
      labels:
        app: aggregatorservice
    spec:
      containers:
      - name: aggregatorservice
        image: tarar290190/aggregatorservice:v.0
        ports:
        - containerPort: 80
        env: 
        - name: UserServiceUrl
          value: http://10.39.245.65
        - name: OrderServiceUrl
          value: http://10.39.245.64
        - name: JaegerURL
          value: 10.39.247.117

---
apiVersion: v1
kind: Service
metadata:
  name: aggregatorservice-development
spec:
  type: LoadBalancer
  selector:
    app: aggregatorservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80