apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql
    template:
      metadata: 
        labels:
          app: mysql
        spec:
          containers:
            - name: mysql
              image: mysql
              ports:
              - containerPorts: 3306
              env:
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef: 
                    name: mysql-secret
                    key: mysql-root-username 
              - name: MYSQL_PASSWORD
                 valueFrom:
                  secretKeyRef: 
                    name: mysql-secret
                    key: mysql-root-password

---
apiVersion: v1
kind: Sevice
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  