apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-development
  labels:
    app: orderservice
spec:
    replicas: 1
    selector:
      matchLabels:
        app: orderservice
    template:
      metadata: 
        labels:
          app: orderservice
        spec:
          containers:
            - name: orderservice
              image: tarar290190/oderservice:v1.0
              ports:
              - containerPorts: 15001

---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
spec:
  selector:
    app: orderservice
  ports:
    - protocol: HTTP
      port: 80
      targetPort: 15001 
      nodePort: 80 