apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-development
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata: 
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: tarar290190/userservice:v2.0
        ports:
        - containerPort: 80
        env: 
        - name: JaegerURL
          value: 10.39.247.117

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      